### ISSUE TITLE
Prepare `history` table for order by `event_time desc, event_type desc`

### ISSUE THREAD

**Issue by nilmerg** [Icinga/icingadb#614] opened 2023-07-07 10:08 UTC
This includes:

* Update `history.event_type` to reflect the correlation of different events (e.g. `downtime_start -> downtime_end`)
* Add an index for `history.event_time desc, history.event_type desc` (not sure if the direction matters being in the definition)

**Comment by julianbrost** [comment] 2023-07-28 13:24
> * Update `history.event_type` to reflect the correlation of different events (e.g. `downtime_start -> downtime_end`)

We discussed that internally yesterday and we want to change the sort order of that enum.

> * Add an index for `history.event_time desc, history.event_type desc` (not sure if the direction matters being in the definition)

I think it's questionable if this would have any benefit over the existing index on `event_time`. Typically, there aren't that many events within the same millisecond so that sorting them on the fly should be slow (but you can get to quite a few events at the same time with downtimes for example). Also, I really have doubts on the general usefulness of an unfiltered list of history events (and any filter applied might make the extra index useless).

**Comment by julianbrost** [comment] 2023-07-31 12:38
My proposal for the new order (events that come earlier are listed first):
* `state_change`
* `downtime_start`
* `downtime_end`
* `comment_add`
* `comment_remove`
* `flapping_end`
* `flapping_start`
* `ack_clear`
* `ack_set`
* `notification`

Rationale (the first two points are required for https://github.com/Icinga/icingadb-web/issues/587, the third one has some justification and the remaining ones are more of an arbitrary choice to come up with some total order):
* `notification` comes last because everything else can cause a notification.
* `state_change` comes before `downtime_start`, `flapping_start`, `flapping_end`, `ack_clear` as all these can be caused by a state change.
* `flapping_end` comes before `flapping_start` and `ack_clear` before `ack_set` as these don't stack (i.e. a checkable can only be acked again after the previous ack was cleared, in contrast to downtimes for example).
* As an extension, all end events come before the corresponding start events, this means that if you read the history timeline and try to remember the current state in your head, this will minimize that state.
* The remaining ambiguities are resolved by sorting alphabetically.

> * Update `history.event_type` to reflect the correlation of different events (e.g. `downtime_start -> downtime_end`)

@nilmerg If I understand correctly, you would want `downtime_start` before `downtime_end`, which is different from my suggestion. Do you have a particular reason why you would want it that way around? My reasoning is that if there are both event time at the same time, it's more likely that these were different downtimes, so if the end event comes earlier, it's sorted closer to the corresponding start event in the past. If it was the same downtime, that order would of course be incorrect, but it would imply a downtime with a duration less than 1ms.

This also show the limitation of this approach: it should be good enough for addressing https://github.com/Icinga/icingadb-web/issues/587, but there will be some edge-cases where it won't be perfect, but still no worse than the old behavior (no defined sort order).

**Comment by nilmerg** [comment] 2023-07-31 14:21
> Do you have a particular reason why you would want it that way around?

No. It was just an example I've used when creating the issue. (Without thinking it through)

**Closed** 2023-08-07 11:08 UTC
