### ISSUE TITLE
Service check is overdue if outside the time period

### ISSUE THREAD

**Issue by arburg-dmoser** [Icinga/icingadb#763] opened 2024-06-10 08:05 UTC
## Service check is overdue if outside the defined time period

We have implemented a check that only runs in the morning between 6 and 7 am. Outside the time period, IcingaDB Web shows the service as overdue.

![image](https://github.com/Icinga/icingadb/assets/78567693/6fb223bc-04b8-4208-b5ca-7418975877da)

```
template Service "check-nrpe-linux-updates" {
    check_command = "check_nrpe_yum"
    max_check_attempts = "1"
    check_period = "only_6-7"
    check_interval = 30m
    retry_interval = 5m
    check_timeout = 15m
    enable_notifications = true
    enable_active_checks = true
    enable_passive_checks = false
    enable_event_handler = true
    enable_flapping = false
    enable_perfdata = false
}
```

```
object TimePeriod "only_6-7" {
    import "[legacy-timeperiod](...)"
    display_name = "Inspection only between 6 and 7 a.m."
    ranges = {
        "friday"	= "06:00-07:00"
        "monday"	= "06:00-07:00"
        "saturday"	= "06:00-07:00"
        "sunday"	= "06:00-07:00"
        "thursday"	= "06:00-07:00"
        "tuesday"	= "06:00-07:00"
        "wednesday"	= "06:00-07:00"
    }
}
```

## Expected behavior

The service should not receive the status overdue if no execution is scheduled.

## Your Environment

* Icinga DB version: 1.1.2
* Icinga 2 version: 2.12.1
* Operating System and version: Red Hat Enterprise Linux release 8.10 (Ootpa)

**Comment by julianbrost** [comment] 2024-06-10 09:09
That sounds like a duplicate of #667.

**Closed as not planned by julianbrost** 2024-06-10 09:09 UTC
