### ISSUE TITLE
Observance of time period for the detection of overdue checks

### ISSUE THREAD

**Issue by mwaldmueller** [Icinga/icingadb#672] opened 2024-01-24 07:08 UTC
icingadb-web should consider the time period (apart from 24x7) in it's overdue checks. This affects the monitoring views and also the "Overdue" dashboard.

![icingadb-web_overdue](https://github.com/Icinga/icingadb-web/assets/3973350/bd38783e-18b3-4811-bc7c-d39561a8d27a)

# Environment:
Icinga Web 2.12.1
icingadb-web 1.1.1

**Comment by nilmerg** [comment] 2024-01-24 08:01
Duplicate of #667

**Closed by nilmerg** 2024-01-24 08:01 UTC
