### ISSUE TITLE
initscript for non-systemd OS

### ISSUE THREAD

**Issue by wwuck** [Icinga/icingadb#572] opened 2023-03-08 01:31 UTC
I have an icinga2 instance with icingaweb2 and monitoring module running on Devuan 4 (Debian 11 derivative without systemd) working successfully. I am attempting to install icingadb using the instructions at https://icinga.com/docs/icinga-db/latest/doc/02-Installation/03-Debian/ but the icingadb package only provides a systemd service file.  I am using the icinga APT repository for all icinga related packages.

Can you please add a initscript `/etc/init.d/icingadb` for non-sytemd users?  I can see that `icingadb-redis-server` already provides an initscript.

**Comment by wwuck** [comment] 2023-03-08 02:25
Ahh just noticed the icinga-packaging repository.

https://github.com/Icinga/icinga-packaging/issues/281

**Comment by htriem** [comment] 2023-03-14 10:21
Duplicate of [icinga-packaging/281](https://github.com/Icinga/icinga-packaging/issues/281)

**Closed by htriem** 2023-03-14 10:21 UTC
