### ISSUE TITLE
Ubuntu 24.04 Noble is missing icingadb-redis package

### ISSUE THREAD

**Issue by miguel-ssys** [Icinga/icingadb#764] opened 2024-06-12 22:35 UTC
Hello everyone,

I'm trying to install the icingadb-redis package on Ubuntu 24.04 via apt, but I received a message saying the package doesn't exist. After checking https://packages.icinga.com/, I confirmed that the icingadb-redis package isn't available for Ubuntu 24.04.

Could someone please advise on how to proceed in this situation?

Thanks in advance!

**Comment by fscaptain** [comment] 2024-06-20 20:31
+1

TNX

**Comment by OldWindowsGuy** [comment] 2024-06-21 05:29
+1

**Comment by oxzi** [comment] 2024-06-21 06:31
Thanks for your report. We are aware of this and, as written over at Icinga/icinga-packaging#304, @Al2Klimov is already working on it. New packages should arrive soon.

**Comment by Al2Klimov** [comment] 2024-06-26 11:31
Duplicate of https://github.com/Icinga/icinga-packaging/issues/304

**Closed** 2024-06-26 11:38 UTC
Labels: duplicate
