### ISSUE TITLE
"Error 1406: Data too long for column icon_image_alt" since update to icingadb 1.2.0

### ISSUE THREAD

**Issue by K0nne** [Icinga/icingadb#754] opened 2024-05-02 10:30 UTC
## Describe the bug

Today we installed the latest icingadb release 1.2.0 and performed the schema upgrade. Since then we have the following errors:

```
Error 1406: Data too long for column icon_image_alt at row 1#012cant perform INSERT INTO \service\ (\eventcommand_name\, \properties_checksum\, \event_handler_enabled\, \max_check_attempts\, \name_ci\, \checkcommand_id\, \notes_url_id\, \active_checks_enabled\, \icon_image_id\, \notes\, \id\, \check_timeperiod_id\, \check_timeout\, \command_endpoint_name\, \eventcommand_id\, \notifications_enabled\, \passive_checks_enabled\, \environment_id\, \name_checksum\, \action_url_id\, \check_timeperiod_name\, \check_retry_interval\, \checkcommand_name\, \command_endpoint_id\, \flapping_threshold_low\, \is_volatile\, \zone_id\, \name\, \host_id\, \icon_image_alt\, \zone_name\, \check_interval\, \display_name\, \flapping_enabled\, \flapping_threshold_high\, \perfdata_enabled\) VALUES (:eventcommand_name, :properties_checksum, :event_handler_enabled, :max_check_attempts, :name_ci, :checkcommand_id, :notes_url_id
, :active_checks_enabled, :icon_image_id, :notes, :id, :check_timeperiod_id, :check_timeout, :command_endpoint_name, :eventcommand_id, :notifications_enabled, :passive_checks_enabled, :environment_id, :name_checksum, :action_url_id, :check_timeperiod_name, :check_retry_interval, :checkcommand_name, :command_endpoint_id, :flapping_threshold_low, :is_volatile, :zone_id, :name, :host_id, :icon_image_alt, :zone_name, :check_interval, :display_name, :flapping_enabled, :flapping_threshold_high, :perfdata_enabled)#012github.com/icinga/icingadb/internal.CantPerformQuery#012#011github.com/icinga/icingadb/internal/internal.go:30#012github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2.1#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:412#012github.com/icinga/icingadb/pkg/retry.WithBackoff#012#011github.com/icinga/icingadb/pkg/retry/retry.go:60#012github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:407#012golang.org/x/sync/errgroup.(*Group)[.Go.func1#012#011golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78#012runtime.goexit#012#011runtime/asm_amd64.s:1695#012retry](mailto:.Go.func1#012#011golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78#012runtime.goexit#012#011runtime/asm_amd64.s:1695#012retry) deadline exceeded#012github.com/icinga/icingadb/pkg/retry.WithBackoff#012#011github.com/icinga/icingadb/pkg/retry/retry.go:95#012github.com/icinga/icingadb/pkg/icingadb.(*DB).NamedBulkExec.func1.(*DB).NamedBulkExec.func1.1.2#012#011github.com/icinga/icingadb/pkg/icingadb/db.go:407#012golang.org/x/sync/errgroup.(*Group)[.Go.func1#012#011golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78#012runtime.goexit#012#011runtime/asm_amd64.s:1695](mailto:.Go.func1#012#011golang.org/x/sync@v0.7.0/errgroup/errgroup.go:78#012runtime.goexit#012#011runtime/asm_amd64.s:1695)

```

```
database: Cant execute query. Retrying.
```

We use the `icon_image_alt` attribute. Our longest entry has 77 chars (one sentence).

## To Reproduce

Use the `icon_image_alt` attribute as stated above and use the latest update.

## Expected behavior

`icon_image_alt` should be supported as before.

## Your Environment

Include as many relevant details about the environment you experienced the problem in

* Icinga DB version: 1.2.0
* Icinga 2 version: 2.13.9
* Operating System and version: RHEL8

**Comment by K0nne** [comment] 2024-05-02 11:14
The source of the issue seems to be #699. Before activating strict mode, too long values were silently truncated.

**Comment by oxzi** [comment] 2024-05-02 12:40
Thanks for your report. I'm closing this one as it is a duplicate of #752.

**Closed by oxzi** 2024-05-02 12:40 UTC
Labels: bug, duplicate
